# Generated by Django 5.2.14 on 2026-05-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsubscription',
            name='plan_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20),
        ),
    ]
