# Generated by Django 5.2.14 on 2026-05-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_downloaded_plan_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='downloaded_plan_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_ai_tracker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_consultations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_diet_plan',
            field=models.BooleanField(default=False),
        ),
    ]
