# Generated by Django 5.2.14 on 2026-05-19 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('articles', 'Articles'), ('recipes', 'Healthy Recipes'), ('wellness', 'Wellness Tips'), ('nutrition', 'Nutrition'), ('success_stories', 'Success Stories')], default='articles', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('author_name', models.CharField(default='NutriLife Team', max_length=100)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
