from django.urls import path
from . import views

urlpatterns = [
    path('profile-stats/', views.get_profile_stats, name='profile-stats'),
    path('update-weight/', views.update_weight, name='update-weight'),
    path('update-streak/', views.update_streak, name='update-streak'),
    path('weight-history/', views.get_weight_history, name='weight-history'),
    path('achievements/', views.get_achievements, name='achievements'),
    path('weekly-report/', views.get_weekly_report, name='weekly-report'),
    path('calendar/', views.get_patient_calendar, name='patient-calendar'),
    path('active-diet-plan/', views.get_active_diet_plan, name='active-diet-plan'),
    path('today-meals-checklist/', views.get_today_meals_checklist, name='today-meals-checklist'),
    path('complete-meal-checklist/<int:checklist_id>/', views.complete_meal_checklist, name='complete-meal-checklist'),
    path('complete-payment/', views.complete_payment, name='complete-payment'),
    path('my-plan/', views.get_my_plan, name='my-plan'),
    path('invoices/', views.get_invoices, name='invoices'),
    path('conversations/', views.get_conversations, name='conversations'),
    path('messages/<int:user_id>/', views.get_messages, name='messages'),
    path('send-message/', views.send_message, name='send-message'),
    path('my-nutritionist/', views.get_my_nutritionist, name='my_nutritionist'),
    path('assign-nutritionist/', views.assign_nutritionist, name='assign_nutritionist'),
    path('my-diet-plans/', views.get_my_diet_plans, name='my-diet-plans'),
    path('my-notifications/', views.get_my_notifications, name='my-notifications'),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark-notification-read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark-all-notifications-read'),
    path('add-meal-checklist/', views.add_meal_checklist, name='add_meal_checklist'),
    path('my-subscription/', views.get_my_subscription, name='my_subscription'),
    path('invoices/', views.get_invoices, name='invoices'),
    path('invoice/<int:invoice_id>/download/', views.download_invoice, name='download_invoice'),
    path('diet-plan/<int:plan_id>/download/', views.download_diet_plan_pdf, name='download-diet-plan'),
    path('admin/', views.get_admin_user, name='get-admin'),
    path('generate_meal_checklist_for_plan/', views.generate_meal_checklist_for_plan, name='generate_meal_checklist_for_plan'),
]